id: P006931
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:24.639227
source_metadata:
  id: bdr:W3CN6332
  title: གསུང་ངག་ལམ་འབྲས་སྣང་གསུམ་མཛེས་རྒྱན།
  author: ''
  volumes:
    c300569b49a44903b082110eb5ee542b:
      image_group_id: I3CN6334
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
